// 中国车牌地区数据
export type VehiclePlateRegion = {
  province: string; // 省份名称
  code: string; // 省份简称
  cities: {
    name: string; // 城市名称
    letter: string; // 城市代码字母
  }[];
};

export const vehiclePlateRegions: VehiclePlateRegion[] = [
  {
    province: "北京市",
    code: "京",
    cities: [
      { name: "北京市", letter: "A" },
    ],
  },
  {
    province: "天津市",
    code: "津",
    cities: [
      { name: "天津市", letter: "A" },
    ],
  },
  {
    province: "河北省",
    code: "冀",
    cities: [
      { name: "石家庄市", letter: "A" },
      { name: "唐山市", letter: "B" },
      { name: "秦皇岛市", letter: "C" },
      { name: "邯郸市", letter: "D" },
      { name: "邢台市", letter: "E" },
      { name: "保定市", letter: "F" },
      { name: "张家口市", letter: "G" },
      { name: "承德市", letter: "H" },
      { name: "沧州市", letter: "J" },
      { name: "廊坊市", letter: "R" },
      { name: "衡水市", letter: "T" },
    ],
  },
  {
    province: "山西省",
    code: "晋",
    cities: [
      { name: "太原市", letter: "A" },
      { name: "大同市", letter: "B" },
      { name: "阳泉市", letter: "C" },
      { name: "长治市", letter: "D" },
      { name: "晋城市", letter: "E" },
      { name: "朔州市", letter: "F" },
      { name: "晋中市", letter: "K" },
      { name: "运城市", letter: "M" },
      { name: "忻州市", letter: "H" },
      { name: "临汾市", letter: "L" },
      { name: "吕梁市", letter: "J" },
    ],
  },
  {
    province: "内蒙古自治区",
    code: "蒙",
    cities: [
      { name: "呼和浩特市", letter: "A" },
      { name: "包头市", letter: "B" },
      { name: "乌海市", letter: "C" },
      { name: "赤峰市", letter: "D" },
      { name: "通辽市", letter: "E" },
      { name: "鄂尔多斯市", letter: "K" },
      { name: "呼伦贝尔市", letter: "E" },
      { name: "巴彦淖尔市", letter: "L" },
      { name: "乌兰察布市", letter: "J" },
    ],
  },
  {
    province: "辽宁省",
    code: "辽",
    cities: [
      { name: "沈阳市", letter: "A" },
      { name: "大连市", letter: "B" },
      { name: "鞍山市", letter: "C" },
      { name: "抚顺市", letter: "D" },
      { name: "本溪市", letter: "E" },
      { name: "丹东市", letter: "F" },
      { name: "锦州市", letter: "G" },
      { name: "营口市", letter: "H" },
      { name: "阜新市", letter: "J" },
      { name: "辽阳市", letter: "K" },
      { name: "盘锦市", letter: "L" },
      { name: "铁岭市", letter: "M" },
      { name: "朝阳市", letter: "N" },
      { name: "葫芦岛市", letter: "P" },
    ],
  },
  {
    province: "吉林省",
    code: "吉",
    cities: [
      { name: "长春市", letter: "A" },
      { name: "吉林市", letter: "B" },
      { name: "四平市", letter: "C" },
      { name: "辽源市", letter: "D" },
      { name: "通化市", letter: "E" },
      { name: "白山市", letter: "F" },
      { name: "松原市", letter: "J" },
      { name: "白城市", letter: "G" },
      { name: "延边朝鲜族自治州", letter: "H" },
    ],
  },
  {
    province: "黑龙江省",
    code: "黑",
    cities: [
      { name: "哈尔滨市", letter: "A" },
      { name: "齐齐哈尔市", letter: "B" },
      { name: "牡丹江市", letter: "C" },
      { name: "佳木斯市", letter: "D" },
      { name: "大庆市", letter: "E" },
      { name: "伊春市", letter: "F" },
      { name: "鸡西市", letter: "G" },
      { name: "鹤岗市", letter: "H" },
      { name: "七台河市", letter: "K" },
      { name: "黑河市", letter: "N" },
      { name: "双鸭山", letter: "J" },
      { name: "绥化市", letter: "M" },
      { name: "大兴安岭地区", letter: "P" },
    ],
  },
  {
    province: "上海市",
    code: "沪",
    cities: [
      { name: "上海市", letter: "A" },
    ],
  },
  {
    province: "江苏省",
    code: "苏",
    cities: [
      { name: "南京市", letter: "A" },
      { name: "无锡市", letter: "B" },
      { name: "徐州市", letter: "C" },
      { name: "常州市", letter: "D" },
      { name: "苏州市", letter: "E" },
      { name: "南通市", letter: "F" },
      { name: "连云港市", letter: "G" },
      { name: "淮安市", letter: "H" },
      { name: "盐城市", letter: "J" },
      { name: "扬州市", letter: "K" },
      { name: "镇江市", letter: "L" },
      { name: "泰州市", letter: "M" },
      { name: "宿迁市", letter: "N" },
    ],
  },
  {
    province: "浙江省",
    code: "浙",
    cities: [
      { name: "杭州市", letter: "A" },
      { name: "宁波市", letter: "B" },
      { name: "温州市", letter: "C" },
      { name: "嘉兴市", letter: "F" },
      { name: "湖州市", letter: "E" },
      { name: "绍兴市", letter: "D" },
      { name: "金华市", letter: "G" },
      { name: "衢州市", letter: "H" },
      { name: "舟山市", letter: "L" },
      { name: "台州市", letter: "J" },
      { name: "丽水市", letter: "K" },
    ],
  },
  {
    province: "安徽省",
    code: "皖",
    cities: [
      { name: "合肥市", letter: "A" },
      { name: "芜湖市", letter: "B" },
      { name: "蚌埠市", letter: "C" },
      { name: "淮南市", letter: "D" },
      { name: "马鞍山市", letter: "E" },
      { name: "淮北市", letter: "F" },
      { name: "铜陵市", letter: "G" },
      { name: "安庆市", letter: "H" },
      { name: "黄山市", letter: "J" },
      { name: "滁州市", letter: "M" },
      { name: "阜阳市", letter: "K" },
      { name: "宿州市", letter: "L" },
      { name: "六安市", letter: "N" },
      { name: "亳州市", letter: "S" },
      { name: "池州市", letter: "R" },
      { name: "宣城市", letter: "P" },
    ],
  },
  {
    province: "福建省",
    code: "闽",
    cities: [
      { name: "福州市", letter: "A" },
      { name: "厦门市", letter: "D" },
      { name: "莆田市", letter: "B" },
      { name: "三明市", letter: "G" },
      { name: "泉州市", letter: "C" },
      { name: "漳州市", letter: "E" },
      { name: "南平市", letter: "H" },
      { name: "龙岩市", letter: "F" },
      { name: "宁德市", letter: "J" },
    ],
  },
  {
    province: "江西省",
    code: "赣",
    cities: [
      { name: "南昌市", letter: "A" },
      { name: "景德镇市", letter: "H" },
      { name: "萍乡市", letter: "B" },
      { name: "九江市", letter: "G" },
      { name: "新余市", letter: "K" },
      { name: "鹰潭市", letter: "L" },
      { name: "赣州市", letter: "B" },
      { name: "吉安市", letter: "D" },
      { name: "宜春市", letter: "C" },
      { name: "抚州市", letter: "F" },
      { name: "上饶市", letter: "E" },
    ],
  },
  {
    province: "山东省",
    code: "鲁",
    cities: [
      { name: "济南市", letter: "A" },
      { name: "青岛市", letter: "B" },
      { name: "淄博市", letter: "C" },
      { name: "枣庄市", letter: "D" },
      { name: "东营市", letter: "E" },
      { name: "烟台市", letter: "F" },
      { name: "潍坊市", letter: "G" },
      { name: "济宁市", letter: "H" },
      { name: "泰安市", letter: "J" },
      { name: "威海市", letter: "K" },
      { name: "日照市", letter: "L" },
      { name: "临沂市", letter: "Q" },
      { name: "德州市", letter: "N" },
      { name: "聊城市", letter: "P" },
      { name: "滨州市", letter: "M" },
      { name: "菏泽市", letter: "R" },
    ],
  },
  {
    province: "河南省",
    code: "豫",
    cities: [
      { name: "郑州市", letter: "A" },
      { name: "开封市", letter: "B" },
      { name: "洛阳市", letter: "C" },
      { name: "平顶山市", letter: "D" },
      { name: "安阳市", letter: "E" },
      { name: "鹤壁市", letter: "F" },
      { name: "新乡市", letter: "G" },
      { name: "焦作市", letter: "H" },
      { name: "濮阳市", letter: "J" },
      { name: "许昌市", letter: "K" },
      { name: "漯河市", letter: "L" },
      { name: "三门峡市", letter: "M" },
      { name: "南阳市", letter: "R" },
      { name: "商丘市", letter: "N" },
      { name: "信阳市", letter: "S" },
      { name: "周口市", letter: "P" },
      { name: "驻马店市", letter: "Q" },
    ],
  },
  {
    province: "湖北省",
    code: "鄂",
    cities: [
      { name: "武汉市", letter: "A" },
      { name: "黄石市", letter: "B" },
      { name: "十堰市", letter: "C" },
      { name: "宜昌市", letter: "E" },
      { name: "襄阳市", letter: "F" },
      { name: "鄂州市", letter: "G" },
      { name: "荆门市", letter: "H" },
      { name: "孝感市", letter: "K" },
      { name: "荆州市", letter: "D" },
      { name: "黄冈市", letter: "J" },
      { name: "咸宁市", letter: "L" },
      { name: "随州市", letter: "S" },
      { name: "恩施土家族苗族自治州", letter: "Q" },
    ],
  },
  {
    province: "湖南省",
    code: "湘",
    cities: [
      { name: "长沙市", letter: "A" },
      { name: "株洲市", letter: "B" },
      { name: "湘潭市", letter: "C" },
      { name: "衡阳市", letter: "D" },
      { name: "邵阳市", letter: "E" },
      { name: "岳阳市", letter: "F" },
      { name: "常德市", letter: "J" },
      { name: "张家界市", letter: "G" },
      { name: "益阳市", letter: "H" },
      { name: "郴州市", letter: "L" },
      { name: "永州市", letter: "M" },
      { name: "怀化市", letter: "N" },
      { name: "娄底市", letter: "K" },
      { name: "湘西土家族苗族自治州", letter: "U" },
    ],
  },
  {
    province: "广东省",
    code: "粤",
    cities: [
      { name: "广州市", letter: "A" },
      { name: "韶关市", letter: "F" },
      { name: "深圳市", letter: "B" },
      { name: "珠海市", letter: "C" },
      { name: "汕头市", letter: "D" },
      { name: "佛山市", letter: "E" },
      { name: "江门市", letter: "J" },
      { name: "湛江市", letter: "G" },
      { name: "茂名市", letter: "K" },
      { name: "肇庆市", letter: "H" },
      { name: "惠州市", letter: "L" },
      { name: "梅州市", letter: "M" },
      { name: "汕尾市", letter: "N" },
      { name: "河源市", letter: "P" },
      { name: "阳江市", letter: "Q" },
      { name: "清远市", letter: "R" },
      { name: "东莞市", letter: "S" },
      { name: "中山市", letter: "T" },
      { name: "潮州市", letter: "U" },
      { name: "揭阳市", letter: "V" },
      { name: "云浮市", letter: "W" },
    ],
  },
  {
    province: "广西壮族自治区",
    code: "桂",
    cities: [
      { name: "南宁市", letter: "A" },
      { name: "柳州市", letter: "B" },
      { name: "桂林市", letter: "C" },
      { name: "梧州市", letter: "D" },
      { name: "北海市", letter: "E" },
      { name: "防城港市", letter: "P" },
      { name: "钦州市", letter: "N" },
      { name: "贵港市", letter: "R" },
      { name: "玉林市", letter: "K" },
      { name: "百色市", letter: "L" },
      { name: "贺州市", letter: "J" },
      { name: "河池市", letter: "M" },
      { name: "来宾市", letter: "G" },
      { name: "崇左市", letter: "F" },
    ],
  },
  {
    province: "海南省",
    code: "琼",
    cities: [
      { name: "海口市", letter: "A" },
      { name: "三亚市", letter: "B" },
    ],
  },
  {
    province: "重庆市",
    code: "渝",
    cities: [
      { name: "重庆市", letter: "A" },
    ],
  },
  {
    province: "四川省",
    code: "川",
    cities: [
      { name: "成都市", letter: "A" },
      { name: "自贡市", letter: "C" },
      { name: "攀枝花市", letter: "D" },
      { name: "泸州市", letter: "E" },
      { name: "德阳市", letter: "F" },
      { name: "绵阳市", letter: "B" },
      { name: "广元市", letter: "H" },
      { name: "遂宁市", letter: "J" },
      { name: "内江市", letter: "K" },
      { name: "乐山市", letter: "L" },
      { name: "南充市", letter: "R" },
      { name: "眉山市", letter: "Z" },
      { name: "宜宾市", letter: "Q" },
      { name: "广安市", letter: "X" },
      { name: "达州市", letter: "S" },
      { name: "雅安市", letter: "T" },
      { name: "巴中市", letter: "Y" },
      { name: "资阳市", letter: "M" },
    ],
  },
  {
    province: "贵州省",
    code: "贵",
    cities: [
      { name: "贵阳市", letter: "A" },
      { name: "六盘水市", letter: "B" },
      { name: "遵义市", letter: "C" },
      { name: "安顺市", letter: "D" },
      { name: "毕节市", letter: "F" },
      { name: "铜仁市", letter: "D" },
      { name: "黔西南布依族苗族自治州", letter: "E" },
      { name: "黔东南苗族侗族自治州", letter: "H" },
      { name: "黔南布依族苗族自治州", letter: "J" },
    ],
  },
  {
    province: "云南省",
    code: "云",
    cities: [
      { name: "昆明市", letter: "A" },
      { name: "曲靖市", letter: "D" },
      { name: "玉溪市", letter: "F" },
      { name: "保山市", letter: "J" },
      { name: "昭通市", letter: "C" },
      { name: "丽江市", letter: "P" },
      { name: "普洱市", letter: "G" },
      { name: "临沧市", letter: "S" },
    ],
  },
  {
    province: "西藏自治区",
    code: "藏",
    cities: [
      { name: "拉萨市", letter: "A" },
    ],
  },
  {
    province: "陕西省",
    code: "陕",
    cities: [
      { name: "西安市", letter: "A" },
      { name: "铜川市", letter: "B" },
      { name: "宝鸡市", letter: "C" },
      { name: "咸阳市", letter: "D" },
      { name: "渭南市", letter: "E" },
      { name: "延安市", letter: "J" },
      { name: "汉中市", letter: "F" },
      { name: "榆林市", letter: "K" },
      { name: "安康市", letter: "G" },
      { name: "商洛市", letter: "H" },
    ],
  },
  {
    province: "甘肃省",
    code: "甘",
    cities: [
      { name: "兰州市", letter: "A" },
      { name: "嘉峪关市", letter: "B" },
      { name: "金昌市", letter: "C" },
      { name: "白银市", letter: "D" },
      { name: "天水市", letter: "E" },
      { name: "武威市", letter: "H" },
      { name: "张掖市", letter: "G" },
      { name: "平凉市", letter: "L" },
      { name: "酒泉市", letter: "F" },
      { name: "庆阳市", letter: "M" },
      { name: "定西市", letter: "J" },
      { name: "陇南市", letter: "K" },
    ],
  },
  {
    province: "青海省",
    code: "青",
    cities: [
      { name: "西宁市", letter: "A" },
    ],
  },
  {
    province: "宁夏回族自治区",
    code: "宁",
    cities: [
      { name: "银川市", letter: "A" },
      { name: "石嘴山市", letter: "B" },
      { name: "吴忠市", letter: "C" },
      { name: "固原市", letter: "D" },
      { name: "中卫市", letter: "E" },
    ],
  },
  {
    province: "新疆维吾尔自治区",
    code: "新",
    cities: [
      { name: "乌鲁木齐市", letter: "A" },
      { name: "克拉玛依市", letter: "B" },
    ],
  },
];
